- name: create Aws Instances and R53 records
  hosts: localhost
  vars:
    zone: daws304.online
  tasks:
  - name: create EC2 instances
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      name: "{{ item }}"
      security_group: allow-everything
      image_id: ami-090252cbe067a9e58
      tags:
        Name: "{{ item }}"
    loop:
    - db
    - backend
    - frontend
    register: ec2_instances_info

  - name: Print Info
    ansible.builtin.debug:
      msg: "{{ ec2_instances_info }}"

# - name: Create R53 records
#   amazon.aws.route53:
#   record: 